### ISSUE TITLE
Forum post is ready 

### ISSUE THREAD

**Issue by holmesworcester** [ZcashFoundation/zomg#18]
Let's draft it in this doc here: https://docs.google.com/document/d/1TjiDeLI9O8KltYW3fyZbIZO1ugiT_-voyIElru-KKEI/edit#heading=h.nhh5w1k1sorx

**Comment by mineZcash** [comment]
I am happy with your forum post draft as-is. Nice work.

**Comment by holmesworcester** [comment]
thanks!
