### ISSUE TITLE
Github project has our logo

### ISSUE THREAD

**Issue by holmesworcester** [ZcashFoundation/zomg#20]
@mineZcash, can you upload a logo with the right dimensions here?

https://github.com/ZcashFoundation/zomg/settings

**Comment by mineZcash** [comment]
We still have to decide what the final logo design is. #4

**Comment by mineZcash** [comment]
Added this version as the repos logo, can change if format is not preferred.

<img width="300" alt="Repo_Logo" src="https://user-images.githubusercontent.com/27791307/101284892-71ec1080-37b0-11eb-9d97-ceb62cd2d0ef.png">
