### ISSUE TITLE
Logo is final

### ISSUE THREAD

**Issue by holmesworcester** [ZcashFoundation/zomg#4]
We need to decide on a final logo. Upfront feedback is helpful!

**Comment by mineZcash** [comment]
So I spent some time thinking about the format, a grown tree will always be in a vertical format, the circuit board thing is a bit too much. Here is another shot, keep it simple:

Hand giving away Zcash to grow the ecosystem: Zcash Ongoing Major Grants

<img width="200" alt="ZOMG_Color_text" src="https://user-images.githubusercontent.com/27791307/99911172-8dd7b880-2cc0-11eb-9349-33a9be3ac7d0.png">
<img width="200" alt="ZOMG_Color" src="https://user-images.githubusercontent.com/27791307/99910473-3fc0b600-2cbc-11eb-951c-732d7876f470.png">
<img width="200" alt="ZOMG_B_W" src="https://user-images.githubusercontent.com/27791307/99910989-68967a80-2cbf-11eb-91c8-69539ace8a64.png">
<img width="200" alt="ZOMG_Color_blank" src="https://user-images.githubusercontent.com/27791307/99911033-b1e6ca00-2cbf-11eb-98f7-63d0e390d318.png">



The good thing is that it makes sense in B&W or with full Color. It is a square format, and we can choose to have text or no text, or ZOMG at the bottom and it still looks correct.

**Comment by holmesworcester** [comment]
Something about the hand and the text seems a little weird for me. The typography on the text feels kind of opinionated in the wrong direction, and the hand looks very thick or "uncanny valley" in some way.

The Zcash coin with the leaves feels super nice and chill and normal and feels like a great place to build from. I wonder if “ZOMG" would work to the right of the coin and leaf, with the acronym and the full text below, in a very conservative font, perhaps using the same font that the Zcash Foundation uses? (Or is that already it?)     

If it’s weird for the “Z” to show up twice, we could use a lock icon in the coin to represent private money. And we could put the dollar sign lines on the first Z in ZOMG potentially. 

Again, giving this in the spirit of my best frank feedback! I recognize that this stuff is super hard and I’m grateful for the work you’re putting in.

**Comment by Souptacular** [comment]
I agree that the font could be improved:

For fonts I think these are good candidates (no particular order):

https://www.dafont.com/bebas-neue.font (https://github.com/dharmatype/Bebas-Neue for details)
https://www.dafont.com/roboto.font
https://www.dafont.com/louis-george-caf.font

**Comment by mineZcash** [comment]
>Logo is live and seems to resize properly from the large version.

Why has the hand holding the Zcash flower been left off of the website @holmesworcester ? Last MGRC meeting the majority agreed to use it as the interim logo until we can hire a professional graphic designer. 

If you need other formatting to get it to fit properly on the web page just let me know what sizes are needed.

**Comment by mineZcash** [comment]
Will this one work better for the header? 
Transparent background, horizontal format
<img width="540" alt="zomg_header" src="https://user-images.githubusercontent.com/27791307/101284191-becde800-37ac-11eb-9a08-6178327d515e.png">

**Comment by mineZcash** [comment]
<img width="320" alt="zomg_twitter1" src="https://user-images.githubusercontent.com/27791307/101299191-3d537580-37ff-11eb-9164-3dd95676aa0e.png">
<img width="320" alt="zomg_twitter2" src="https://user-images.githubusercontent.com/27791307/101299192-3dec0c00-37ff-11eb-94b5-26840e866ca7.png">

**Comment by mineZcash** [comment]
@holmesworcester I was able to swap the logo but am unsure how to resize, could be a bit bigger.

Also, do we want to adjust the themes color scheme to be more Zcash? ie: black, yellow, grey, green?

**Comment by holmesworcester** [comment]
I was thinking about the color. Let’s make an issue for that.

**Comment by holmesworcester** [comment]
issue created https://github.com/ZcashFoundation/zomg/issues/23
